Destroy all

diff --git a/.github/actions/terragrunt-action/action.yaml b/.github/actions/terragrunt-action/action.yaml
--- a/.github/actions/terragrunt-action/action.yaml
+++ b/.github/actions/terragrunt-action/action.yaml
@@ -89,61 +89,61 @@ runs:
         # terraform_version: ${{ env.tf_version }}
         terraform_wrapper: true
 
-    # - name: Setup Terraform version
-    #   run: terraform --version
-    #   shell: bash
+    - name: Setup Terraform version
+      run: terraform --version
+      shell: bash
 
-    # - name: Setup Terraform wrapper path
-    #   run: which terraform
-    #   shell: bash
+    - name: Setup Terraform wrapper path
+      run: which terraform
+      shell: bash
 
-    # - name: Terragrunt Destroy ${{ inputs.environment_name }}
+    - name: Terragrunt Destroy ${{ inputs.environment_name }}
+      uses: gruntwork-io/terragrunt-action@v2
+      with:
+        tf_version: ${{ inputs.tf_version }}
+        tg_version: ${{ inputs.tg_version }}
+        tg_dir: ${{ inputs.working_dir }}
+        tg_command: 'run-all destroy'
+
+
+
+    # - name: Terragrunt Plan ${{ inputs.environment_name }}
     #   uses: gruntwork-io/terragrunt-action@v2
     #   with:
     #     tf_version: ${{ inputs.tf_version }}
     #     tg_version: ${{ inputs.tg_version }}
     #     tg_dir: ${{ inputs.working_dir }}
-    #     tg_command: 'run-all destroy'
+    #     # tg_command: 'run-all plan --terragrunt-log-level debug'
+    #     tg_command: 'run-all plan'
 
 
 
-    - name: Terragrunt Plan ${{ inputs.environment_name }}
-      uses: gruntwork-io/terragrunt-action@v2
-      with:
-        tf_version: ${{ inputs.tf_version }}
-        tg_version: ${{ inputs.tg_version }}
-        tg_dir: ${{ inputs.working_dir }}
-        # tg_command: 'run-all plan --terragrunt-log-level debug'
-        tg_command: 'run-all plan'
-
-
-
-    - name: Checkov GitHub Action
-      uses: bridgecrewio/checkov-action@v12
-      with:
-        # This will add both a CLI output to the console and create a results.sarif file
-        output_format: cli,sarif
-        output_file_path: console,results.sarif
+    # - name: Checkov GitHub Action
+    #   uses: bridgecrewio/checkov-action@v12
+    #   with:
+    #     # This will add both a CLI output to the console and create a results.sarif file
+    #     output_format: cli,sarif
+    #     output_file_path: console,results.sarif
       
-    # # - name: Upload SARIF file
-    # #   uses: github/codeql-action/upload-sarif@v3     
-    # #   # Results are generated only on a success or failure
-    # #   # this is required since GitHub by default won't run the next step
-    # #   # when the previous one has failed. Security checks that do not pass will 'fail'.
-    # #   # An alternative is to add `continue-on-error: true` to the previous step
-    # #   # Or 'soft_fail: true' to checkov.
-    # #   if: success() || failure()
-    # #   with:
-    # #     sarif_file: results.sarif
+    # # # - name: Upload SARIF file
+    # # #   uses: github/codeql-action/upload-sarif@v3     
+    # # #   # Results are generated only on a success or failure
+    # # #   # this is required since GitHub by default won't run the next step
+    # # #   # when the previous one has failed. Security checks that do not pass will 'fail'.
+    # # #   # An alternative is to add `continue-on-error: true` to the previous step
+    # # #   # Or 'soft_fail: true' to checkov.
+    # # #   if: success() || failure()
+    # # #   with:
+    # # #     sarif_file: results.sarif
 
-    - name: Terragrunt Apply ${{ inputs.environment_name }}
-      # if: ${{ inputs.apply == true }}
-      uses: gruntwork-io/terragrunt-action@v2
-      with:
-        tf_version: ${{ inputs.tf_version }}
-        tg_version: ${{ inputs.tg_version }}
-        tg_dir: ${{ inputs.working_dir }}
-        tg_command: 'run-all apply'
+    # - name: Terragrunt Apply ${{ inputs.environment_name }}
+    #   # if: ${{ inputs.apply == true }}
+    #   uses: gruntwork-io/terragrunt-action@v2
+    #   with:
+    #     tf_version: ${{ inputs.tf_version }}
+    #     tg_version: ${{ inputs.tg_version }}
+    #     tg_dir: ${{ inputs.working_dir }}
+    #     tg_command: 'run-all apply'
 
 
 
